var currentPath='/';
var KNOWN_DIRS=['/profiles/','/backup/','/logs/','/web/'];
function navigateTo(p){currentPath=p;updateBreadcrumb(p);loadPath(p);var b=document.getElementById('btn-del-folder');if(b)b.hidden=(p==='/');var l=document.getElementById('current-path-label');if(l)l.textContent=p;}
function updateBreadcrumb(p){var bc=document.getElementById('breadcrumb');if(!bc)return;bc.innerHTML='<span onclick="navigateTo(\'/\')">/ root</span>';if(p==='/')return;var parts=p.split('/').filter(function(x){return x;});var built='/';parts.forEach(function(x){built+=x+'/';var sep=document.createElement('span');sep.textContent=' > ';var lnk=document.createElement('span');lnk.textContent=x;lnk.style.color='#90caf9';lnk.style.cursor='pointer';(function(c){lnk.onclick=function(){navigateTo(c);};})(built);bc.appendChild(sep);bc.appendChild(lnk);});}
function refreshCurrent(){navigateTo(currentPath);}
function closeViewer(){var v=document.getElementById('viewer-wrap');var c=document.getElementById('viewer-content');if(v)v.hidden=true;if(c)c.style.display='none';}
function loadPath(path){var list=document.getElementById('file-list');if(!list)return;list.innerHTML='<li class=empty>Ladowanie...</li>';closeViewer();if(path==='/'){list.innerHTML='';KNOWN_DIRS.forEach(function(dir){var li=document.createElement('li');li.className='folder-item';li.innerHTML='<span class=fname>'+dir+'</span><div class=factions><button class=btn-view onclick="navigateTo(\''+dir+'\');event.stopPropagation()">Otworz</button><button class=btn-del onclick="clearFolder(\''+dir+'\');event.stopPropagation()">Wyczysc</button></div>';list.appendChild(li);});return;}
fetch('/files/list?dir='+encodeURIComponent(path),{credentials:'include'}).then(function(r){return r.json();}).then(function(data){list.innerHTML='';var files=(data.files||[]).filter(function(f){return!f.name.endsWith('.dir');});if(!files.length){list.innerHTML='<li class=empty>Folder pusty</li>';return;}files.forEach(function(f){var name=f.name.split('/').pop();var li=document.createElement('li');li.className='folder-item';li.innerHTML='<span class=fname>'+name+'</span><span class=fsize>'+f.name+'</span><div class=factions><button class=btn-view onclick="viewFile(\''+f.name+'\');event.stopPropagation()">Podglad</button><button class=btn-dl onclick="downloadFile(\''+f.name+'\');event.stopPropagation()">Pobierz</button><button class=btn-del onclick="deleteFile(\''+f.name+'\');event.stopPropagation()">Usun</button></div>';list.appendChild(li);});}).catch(function(){list.innerHTML='<li class=empty style="color:#f44336">Blad</li>';});}
function viewFile(path){fetch('/files/read?path='+encodeURIComponent(path)).then(function(r){return r.text();}).then(function(t){var vp=document.getElementById('viewer-path');var vc=document.getElementById('viewer-content');var vw=document.getElementById('viewer-wrap');if(!vp||!vc||!vw)return;vp.textContent=path;vc.textContent=t;vc.style.display='block';vw.hidden=false;vc.scrollIntoView({behavior:'smooth'});}).catch(function(){alert('Blad odczytu');});}
function downloadFile(path){fetch('/files/read?path='+encodeURIComponent(path)).then(function(r){return r.text();}).then(function(t){var blob=new Blob([t],{type:'text/plain;charset=utf-8'});var url=URL.createObjectURL(blob);var a=document.createElement('a');a.href=url;a.download=path.split('/').pop();document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);}).catch(function(){alert('Blad pobierania');});}
function deleteFile(path){if(!confirm('Usunac: '+path+'?'))return;fetch('/files/delete?path='+encodeURIComponent(path),{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.ok)refreshCurrent();else alert('Blad: '+(d.message||'?'));}).catch(function(){alert('Blad polaczenia');});}
function clearFolder(dir){if(!confirm('Usunac wszystkie pliki z '+dir+'?'))return;fetch('/files/list?dir='+encodeURIComponent(dir)).then(function(r){return r.json();}).then(function(data){var files=(data.files||[]).filter(function(f){return!f.name.endsWith('.dir');});if(!files.length){alert('Folder pusty.');return;}Promise.all(files.map(function(f){return fetch('/files/delete?path='+encodeURIComponent(f.name),{method:'POST'});})).then(function(){alert('Usunieto '+files.length+' plikow z '+dir);if(document.getElementById('file-list'))refreshCurrent();loadFlashInfo();});});}
function deleteFolder(){if(currentPath!=='/')clearFolder(currentPath);}
function loadFlashInfo(){fetch('/flash/info',{credentials:'include'}).then(function(r){return r.json();}).then(function(d){var st=document.getElementById('flashStatus');if(st)st.textContent=d.ok?'OK (W25Q128)':'Blad';var jd=document.getElementById('flashJedec');if(jd)jd.textContent=d.jedec||'-';var sz=document.getElementById('flashSize');if(sz)sz.textContent=d.size||'-';var us=document.getElementById('flashUsage');var fb=document.getElementById('flashBar');if(d.ok&&us&&fb){var used=parseInt(d.used)||0;var free=parseInt(d.free)||0;var pct=(used+free)>0?Math.round(used/(used+free)*100):0;us.textContent=used+' zajetych / '+free+' wolnych ('+pct+'%)';fb.style.width=pct+'%';}}).catch(function(){var st=document.getElementById('flashStatus');if(st)st.textContent='Blad polaczenia';});}
document.addEventListener('DOMContentLoaded',function(){loadFlashInfo();if(document.getElementById('file-list')){navigateTo('/');setInterval(loadFlashInfo,30000);}});
